# frozen_string_literal: true

require "bundler/gem_tasks"
require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["src/lotr_tcg_data_ruby/test/**/test_*.rb"]
end

require "lotr_tcg_data_ruby"

task default: :test
